name: Release New Version

on:
  push:
    branches:
      - main

jobs:
  release:
    environment: production

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Fetch Git entire history for all branches and tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - id: setup-node
        name: Use Node from .nvmrc file
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Example step where the github-actions bot makes a git commit
        run: |
          git config user.name github-actions[bot]
          git config user.email jcvalerio@jcvalerio.com

      - name: Install Dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npm run release

      - name: Push commit change manually
        run: |
          git push --follow-tags origin main
