name: Release New Version

on:
  push:
    branches:
      - develop
      - main
jobs:
  release:
    environment: production

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Fetch Git entire history for all branches and tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - id: setup-node
        name: Use Node from .nvmrc file
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      # This step is run when the branch is main
      - if: github.ref == 'refs/heads/main'
        name: Run Semantic Release
        run: npm run semantic-release

      # This step is run when the branch different than main
      - if: github.ref != 'refs/heads/main'
        name: Run Semantic Release
        run: npm run semantic-release -- --dry-run
